### 1.1 벡터 만들기

In [1]:
import numpy as np

vector_row = np.array([1,2,3])

vector_column = np.array([[1],
                        [2],
                        [3]])

넘파이 데이터 구조 = 다차원 배열,  
벡터 = 1차원 배열

In [2]:
#넘파이 배열은 ndarray 클래스의 객체
print(type(vector_row))

<class 'numpy.ndarray'>


In [3]:
#ndarray를 사용하는 방법은 권장하진 않는다.
bad_way = np.ndarray((3,))

In [6]:
vector_row = np.array([1,2,3])

#asarray는 새로운 배열을 만들지 않는다.
new_row = np.asarray(vector_row)
new_row is vector_row

True

In [8]:
#array는 배열이 입력되면 새로운 배열을 만든다.
new_row = np.array(vector_row)
new_row is vector_row

False

In [9]:
#배열을 복사하려는 의도를 명확하게 나타나도록 copy 메서드를 사용.
new_row = vector_row.copy()
new_row is vector_row

False

### 1.2 행렬 만들기

In [12]:
import numpy as np

#행렬 만들기
matrix = np.array([[1,2],
                  [1,2],
                  [1,2]])

In [13]:
#행렬에 특화된 데이터 구조, 그치만 권장하진 않음
matrix_object = np.mat([[1,2],[1,2],[1,2]])

In [14]:
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [24]:
#임의의 값이 채워진 배열을 만듦
empty_matrix = np.empty((3,2))
empty_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
# 0으로 채운 배열
zero_matrix = np.zeros((3,2))
zero_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
# 1로 채운 배열
one_matrix = np.ones((3,2))
one_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
#특정 값으로 채운 배열을 만들려면 full함수 사용
seven_matrix = np.zeros((3,2)) + 7
seven_matrix

array([[7., 7.],
       [7., 7.],
       [7., 7.]])

In [27]:
seven_matrix = np.full((3,2), 7)
seven_matrix

array([[7, 7],
       [7, 7],
       [7, 7]])

### 1.3 희소 행렬 만들기

In [3]:
import numpy as np
from scipy import sparse

#희소 행렬을 만든다.
matrix = np.array([[0,0],[0,1],[3,0]])

In [33]:
#CSR 행렬을 만든다.
# 0이 아닌 애들의 index를 뽑아내서 저장
matrix_sparse = sparse.csr_matrix(matrix)

In [34]:
# 희소 행렬을 출력한다.
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [43]:
matrix_large = np.array([[0,0,0,0,0,0,0,0,0,0],
                         [0,1,0,0,0,0,0,0,0,0],
                         [3,0,0,0,0,0,0,0,0,0]])

matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


In [4]:
#(data, (row, col_index)) 로 구성된 튜플을 전달한다.
# shape 매개변수에서 0을 포함한 행렬의 전체 크기를 지정.
matrix_sparse_2 = sparse.csr_matrix(([1,3],([1,2],[1,0])), shape = (3,10))
print(matrix_sparse_2)

  (1, 1)	1
  (2, 0)	3


In [48]:
#밀집 배열로 변환하는 메서드 = toarray
print(matrix_sparse_2.toarray())

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]


In [49]:
#todense 메서드는 np.matrix 객체를 반환
matrix_sparse_2.todense()

matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

### 1.4 원소 선택하기

In [52]:
#행 벡터 만들기
vector = np.array([1,2,3,4,5,6])

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

#vector의 세번째 원소 선택
vector[2]

3

In [53]:
# matrix의 두번째 행, 두번째 열의 원소 선택
matrix[1,1]

5

In [54]:
#vector의 모든 원소 선택
vector[:]

array([1, 2, 3, 4, 5, 6])

In [56]:
vector[:3]

array([1, 2, 3])

In [57]:
vector[3:]

array([4, 5, 6])

In [58]:
#벡터의 마지막 원소 선택
vector[-1]

6

In [59]:
# 행렬의 첫번째 두 행과 모든 열 선택
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
#행렬의 모든 행과 두번째 열
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [61]:
#행렬의 첫번째 행과 세번째 행 선택
matrix[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [63]:
# (0,1),(2,0) 위치의 원소 선택
matrix[[0,2],[1,0]]

array([2, 7])

In [64]:
#블리언 마스크 배열을 만ㄷ르어 원소를 선택할 수도 있다.
mask = matrix > 5
mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [65]:
matrix[mask]

array([6, 7, 8, 9])

### 1.5 행렬 정보 확인하기

In [69]:
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

matrix.shape

(3, 4)

In [70]:
matrix.size

12

In [72]:
matrix.ndim

2

In [73]:
#원소의 데이터 타입
print(matrix.dtype)

int32


In [74]:
#원소 하나가 차지하는 바이트 크기
print(matrix.itemsize)

4


In [75]:
#배열 전체가 차지하는 바이트 크기
print(matrix.nbytes)

48


### 1.6 벡터화 연산 적용하기

In [77]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

# 100을 더하는 함수를 만들고
add_100 = lambda i : i+100
#벡터화된 함수를 만든다.
vectorized_add_100 = np.vectorize(add_100)
#행렬의 모든 원소에 함수를 적용
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [79]:
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [80]:
matrix + [100,100,100]

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [81]:
matrix + [[100],[100],[100]] 

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

### 1.7 최댓값, 최솟값 찾기

In [84]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np.max(matrix))
print(np.min(matrix))

9
1


In [85]:
# 각 열에서 최댓값을 찾는다.
np.max(matrix, axis = 0)

array([7, 8, 9])

In [86]:
# 각 행에서 최댓값을 찾는다.
np.max(matrix, axis = 1)

array([3, 6, 9])

In [87]:
#keepdims 매개변수를 True로 지정하면 원본 배열과 차원이 똑같아짐
vector_column = np.max(matrix, axis = 1, keepdims=True)

vector_column

array([[3],
       [6],
       [9]])

In [88]:
matrix - vector_column

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

### 1.8 평균, 분산, 표준편차 계산하기

In [91]:
print(np.mean(matrix))
print(np.var(matrix))
print(np.std(matrix))

print(np.mean(matrix,axis=0))

5.0
6.666666666666667
2.581988897471611
[4. 5. 6.]


In [92]:
#편향되지 않은 추정값
np.std(matrix, ddof = 1)

2.7386127875258306

### 1.9 배열 크기 바꾸기

In [94]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [95]:
matrix.size

12

In [96]:
# 행 하나에 열은 가능한 많게
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [97]:
#정수 하나 입력시 그 길이의 1차원 배열을 반환
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [98]:
matrix.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [99]:
matrix.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 1.10 벡터나 행렬 전치하기 

In [101]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [103]:
# 벡터의 전치는 행 벡터를 열 또는 그 반대
np.array([[1,2,3,4,5,6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [104]:
matrix.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [108]:
#transpose는 튜플로 바꿀 차원을 직접 지정할 수도 있다.

matrix = np.array([[[1,2],[3,4],[5,6]], [[7,8],[9,10],[11,12]]])


#두번째와 세번째 차원을 바꾸어 2*2*3 행렬로 만듬
matrix.transpose((0,2,1))

array([[[ 1,  3,  5],
        [ 2,  4,  6]],

       [[ 7,  9, 11],
        [ 8, 10, 12]]])

### 1.11 행렬 펼치기

In [110]:
# 새로운 배열 
matrix.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [111]:
# 넘파이 배열의 뷰를 반환
matrix.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 1.12 행렬의 랭크 구하기

In [113]:
matrix = np.array([[1,1,1],[1,1,10],[1,1,15]])

#행렬의 랭크 반환
np.linalg.matrix_rank(matrix)

2

In [116]:
#행렬의 랭크는 선형 독립적인 행 또는 열 개수이다.

#svd 함수로 특잇값 계산
s = np.linalg.svd(matrix, compute_uv = False)
# 오차를 고려해 0에 가까운 아주 작은 값 지정
np.sum(s > 1e-10)

2

### 1.13 행렬식 계산하기

In [117]:
matrix = np.array([[1,2,3],[2,4,6],[3,8,9]])

In [119]:
#행렬의 행렬식 반환
np.linalg.det(matrix)

0.0

### 1.14 행렬의 대각원소 추출하기

In [120]:
# 대각원소 반환
matrix.diagonal()

array([1, 4, 9])

In [121]:
# 주 대각선 하나 위의 대각원소 반환
matrix.diagonal(offset=1)

array([2, 6])

In [122]:
# 주 대각선 하나 아래의 대각원소 반환
matrix.diagonal(offset=-1)

array([2, 8])

In [123]:
a = np.diag(matrix)
print(a)

[1 4 9]


In [125]:
#1차원 배열이 주어지면 2차원 대각행렬을 만든다.
np.diag(a)

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

### 1.15 행렬의 대각합 계산하기

In [126]:
matrix.trace()

14

In [127]:
print(matrix.trace(offset=1))
print(matrix.trace(offset=-1))

8
10


In [130]:
### 1.16 고윳값과 고유벡터 찾기

matrix = np.array([[1,-1,3],[1,1,6],[3,8,9]])


eigenvalues, eigenvectors = np.linalg.eig(matrix)

eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [131]:
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

대칭행렬일 경우 linalg.eigh 함수를 사용하면 더욱 빠르게 계산

In [133]:
matrix = np.array([[1,-1,3],[-1,1,6],[3,6,9]])

eigenvalues, eigenvectors = np.linalg.eigh(matrix)

### 1.17 점곱 계산하기

In [134]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

np.dot(vector_a, vector_b)

32

In [135]:
vector_a @ vector_b

32

In [137]:
# 스칼라 배열에는 @ 이 적용되지 않는다.
scalar_a = np.array(1)
scalar_b = np.array(2)

np.dot(scalar_a, scalar_b)

2

### 1.19 행렬 덧셈과 뺄셈

In [138]:
matrix_a = np.array([[1,1,1],[1,1,1],[1,1,2]])
matrix_b = np.array([[1,3,1],[1,3,1],[1,3,8]])

np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [139]:
matrix_a + matrix_b
#뺄셈 동일

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

### 1.20 행렬 곱셈

In [140]:
matrix_a @ matrix_b

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [141]:
np.dot(matrix_a, matrix_b)

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [142]:
matrix_a * matrix_b

array([[ 1,  3,  1],
       [ 1,  3,  1],
       [ 1,  3, 16]])

np.matmul 함수와 @ 연산자는 다차원 배열을 두 차원이 단순히 쌓인 것으로 취급

In [143]:
a = np.random.rand(2,1,4,5)
b = np.random.rand(1,3,5,6)

np.dot(a,b).shape

(2, 1, 4, 1, 3, 6)

### 1.20 역행렬

In [144]:
matrix = np.array([[1,4],[2,5]])

np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [145]:
#행렬과 역행렬을 곱한다. = 단위행렬 나옴

matrix @ np.linalg.inv(matrix)

array([[1., 0.],
       [0., 1.]])

In [146]:
#정방행렬이 아닌 행렬의 역행렬
matrix = np.array([[1,4,7],[2,5,8]])

np.linalg.pinv(matrix)

array([[-1.16666667,  1.        ],
       [-0.33333333,  0.33333333],
       [ 0.5       , -0.33333333]])

### 1.21 난수 생성하기

In [147]:
np.random.seed(0)

In [148]:
# 0과 1 사이의 세 개의 실수 난수 생성
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [150]:
#0과 10 사이에 세 개의 정수 난수 생성
np.random.randint(0,11,3)

array([3, 5, 2])

In [151]:
#평균이 0이고 표준편차가 1인 정규분포에서 세 개의 수 
np.random.normal(0,1,3)

array([ 0.95008842, -0.15135721, -0.10321885])

In [152]:
#위치모수가 0이고 스케일(측도모수)이 1인 로지스틱 분포에서 세 개의 수
np.random.logistic(0,1,3)

array([1.33535502, 0.1157086 , 0.27387744])

In [154]:
#1보다 크거나 같고 2보다 작은 세 개의 수
np.random.uniform(2,3,3)

array([2.92559664, 2.07103606, 2.0871293 ])

동일한 결과를 얻으려면 같은 난수를 생성해야한다. 이렇게 동일한 난수를 생성하려면 난수 생성기의 초깃값(정수)를 설정해야한다. 동일한 초깃값을 가진 난수 생성은 늘 같은 결과를 출력하기 때문이다.

In [155]:
np.random.random_sample((2,3))

array([[0.0202184 , 0.83261985, 0.77815675],
       [0.87001215, 0.97861834, 0.79915856]])

In [156]:
np.random.rand(2,3)

array([[0.46147936, 0.78052918, 0.11827443],
       [0.63992102, 0.14335329, 0.94466892]])

In [157]:
np.random.uniform(2,3,(2,3))

array([[2.52184832, 2.41466194, 2.26455561],
       [2.77423369, 2.45615033, 2.56843395]])

In [158]:
#randint함수는 최소값을 포함하고 최댓값은 포함하지 않는 정수 난수를 생성
np.random.randint(0,1,10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [159]:
np.random.standard_normal((2,3))

array([[ 0.4105985 ,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743]])

In [163]:
#np.random.normal(0,1,(2,3))이랑 결과 같음
np.random.randn(2,3)

array([[-1.42001794, -1.70627019,  1.9507754 ],
       [-0.50965218, -0.4380743 , -1.25279536]])

In [164]:
#choice 함수는 배열의 원소 중에서 랜덤하게 지정된 횟수만큼 샘플을 만든다.
# 또는 0~1 사이의 원소 중에서 랜덤하게 샘플 선택

#0~2 사이의 정수 중 랜덤하게 5번 뽑음
np.random.choice([0,1,2],5)

array([0, 2, 1, 1, 1])

In [165]:
np.random.choice(3,5)

array([0, 1, 1, 1, 0])

In [167]:
#shuffle함수는 입력된 배열을 섞는다.
a = np.array([0,1,2,3,4])
np.random.shuffle(a)
a

array([3, 4, 1, 0, 2])

In [168]:
#permutation함수는 입력된 배열의 복사본을 만들어 섞은 후 반환
#정수를 입력하면 0에서 1까지 숫자를 섞은 후 반환

np.random.permutation(a)

array([0, 3, 4, 2, 1])